# **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 1: Data Collection & Curation**

**First we need to connect Google Colab with our Google Drive, so that we can have access to our Google drive within Colab.**

This allows us to:
* Save datasets
* Reload data across sessions
* Organize project files

In [1]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

**Now create "data" folder in our "Colab Notebooks" folder on Google Drive.**

In [ ]:
! mkdir "/content/gdrive/My Drive/Colab Notebooks/data"

## Install and Import Required Libraries
We install the ChEMBL web service package so that we can retrieve bioactivity data

In [2]:
!pip install chembl_webresource_client

Collecting chembl_webresource_client
  Downloading chembl_webresource_client-0.10.9-py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.5.0)
Requirement already satisfied: requests>=2.18.4 in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (2.32.4)
Collecting requests-cache~=1.2 (from chembl_webresource_client)
  Downloading requests_cache-1.2.1-py3-none-any.whl.metadata (9.9 kB)
Requirement already satisfied: easydict in /usr/local/lib/python3.12/dist-packages (from chembl_webresource_client) (1.13)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.18.4->chembl_webresource_client) (2026.1.4)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (25.4.0)
Collecting cattrs>=22.2 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading cattrs-25.3.0-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests-cache~=1.2->chembl_webresource_client) (4.5.1)
Collecting url-normalize>=1.4 (from requests-cache~=1.2->chembl_webresource_client)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in /usr/local/lib/python3.12/dist-packages (from cattrs>=22.2->requests-cache~=1.2->chembl_webresource_client) (4.15.0)
Downloading chembl_webresource_client-0.10.9-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 4.0 MB/s eta 0:00:00
Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.4/61.4 kB 5.2 MB/s eta 0:00:00
Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.7/70.7 kB 6.0 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, cattrs, requests-cache, chembl_webresource_client
Successfully installed cattrs-25.3.0 chembl_webresource_client-0.10.9 requests-cache-1.2.1 url-normalize-2.2.1

# Import Libraries
* pandas for data handling
* new_client from chembl for accessing the database

In [3]:
import pandas as pd
from chembl_webresource_client.new_client import new_client

# Step 1: Search for Traget Protein

## **Target Identification (KRAS)**
Search ChEMBL for the KRAS target and select the most relevant entry.

In [7]:
target = new_client.target
target_query = target.search("BAP1")
targets = pd.DataFrame.from_dict(target_query)
targets.head()

,cross_references,organism,pref_name,score,species_group_flag,target_chembl_id,target_components,target_type,tax_id
0,[],Bothrops asper,Snake venom metalloproteinase BaP1,21.0,False,CHEMBL2079851,"[{'accession': 'P83512', 'component_descriptio...",SINGLE PROTEIN,8722
1,[],Homo sapiens,Ubiquitin carboxyl-terminal hydrolase BAP1,19.0,False,CHEMBL1293314,"[{'accession': 'Q92560', 'component_descriptio...",SINGLE PROTEIN,9606
2,[],Homo sapiens,"Membrane-associated guanylate kinase, WW and P...",13.0,False,CHEMBL4295927,"[{'accession': 'Q96QZ7', 'component_descriptio...",SINGLE PROTEIN,9606
3,[],Homo sapiens,Protein cereblon/E3 ubiquitin-protein ligase R...,12.0,False,CHEMBL6066032,"[{'accession': 'Q96SW2', 'component_descriptio...",PROTEIN-PROTEIN INTERACTION,9606

**Reterive Bioactivity data for selected target**

In [8]:
selected_target = targets.target_chembl_id[0]
selected_target

'CHEMBL2079851'

**Now retrieve only bioactivity data for target; **GTPase KRas(CHEMBL2189121)** with reported IC 50  values in nM (nanomolar) unit.**

In [11]:
activity = new_client.activity
results = activity.filter(target_chembl_id=selected_target).filter(standard_type="IC50")

In [12]:
df1 = pd.DataFrame.from_dict(results)
df1.head(5)

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,11009832,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,0.5
1,None,None,11009833,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,1.2
2,None,None,11009834,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,4.6
3,None,None,11009835,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,30.9
4,None,None,11009836,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,34.2

In [13]:
df1.standard_type.unique()

array(['IC50'], dtype=object)

**Finally Save the resulting bioactivity data to a CSV file** **bioactivity_raw_data.csv**.

In [14]:
df1.to_csv('bioactivity_raw_data.csv', index=False)

**Now copy "bioactivity_raw_data.csv" file to Google Drive, in foler "data"**

In [15]:
! cp bioactivity_raw_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"

In [17]:
! ls -l "/content/gdrive/My Drive/Colab Notebooks/data"

-rw------- 1 root root 14373 Jan 27 09:59 '/content/gdrive/My Drive/Colab Notebooks/data'

In [18]:
! head bioactivity_raw_data.csv

action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,bao_format,bao_label,canonical_smiles,data_validity_comment,data_validity_description,document_chembl_id,document_journal,document_year,ligand_efficiency,molecule_chembl_id,molecule_pref_name,parent_molecule_chembl_id,pchembl_value,potential_duplicate,qudt_units,record_id,relation,src_id,standard_flag,standard_relation,standard_text_value,standard_type,standard_units,standard_upper_value,standard_value,target_chembl_id,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
,,11009832,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@@H](Cc1ccccc1)C(=O)NO,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '14.30', 'le': '0.27', 'lle': '4.98', 'sei': '4.72'}",CHEMBL2089170,,CHEMBL2089170,6.30,0,http://www.openphacts.org/units/Nanomolar,1676534,=,1,1,=,,IC50,nM,,500.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,0.5
,,11009833,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,CNC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](CC(C)C)[C@H](CSc1cccs1)C(=O)NO,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '12.40', 'le': '0.25', 'lle': '2.82', 'sei': '5.51'}",CHEMBL279786,BATIMASTAT,CHEMBL279786,5.92,0,http://www.openphacts.org/units/Nanomolar,1676521,=,1,1,=,,IC50,nM,,1200.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,1.2
,,11009834,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@@H](CCCNC(=N)N)C(=O)NO,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '11.87', 'le': '0.23', 'lle': '6.00', 'sei': '2.73'}",CHEMBL2089172,,CHEMBL2089172,5.34,0,http://www.openphacts.org/units/Nanomolar,1676536,=,1,1,=,,IC50,nM,,4600.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,4.6
,,11009835,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NO,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '9.88', 'le': '0.19', 'lle': '3.48', 'sei': '2.93'}",CHEMBL2089171,,CHEMBL2089171,4.51,0,http://www.openphacts.org/units/Nanomolar,1676535,=,1,1,=,,IC50,nM,,30900.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,30.9
,,11009836,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1c[nH]c2ccccc12)C(=O)N[C@@H](Cc1ccccc1)C(=O)NO,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '9.31', 'le': '0.17', 'lle': '2.67', 'sei': '2.99'}",CHEMBL2089166,,CHEMBL2089166,4.47,0,http://www.openphacts.org/units/Nanomolar,1676530,=,1,1,=,,IC50,nM,,34200.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,34.2
,,11009837,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1c[nH]c2ccccc12)C(=O)N[C@@H](Cc1ccc(O)cc1)C(=O)NO,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '8.75', 'le': '0.16', 'lle': '2.83', 'sei': '2.56'}",CHEMBL2089168,,CHEMBL2089168,4.33,0,http://www.openphacts.org/units/Nanomolar,1676532,=,1,1,=,,IC50,nM,,46200.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,46.2
,,11009838,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,Cl.Nc1ccc(/N=N/c2ccccc2)c(N)n1,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '20.00', 'le': '0.36', 'lle': '1.61', 'sei': '4.76'}",CHEMBL1201022,PHENAZOPYRIDINE HYDROCHLORIDE,CHEMBL1242,4.26,0,http://www.openphacts.org/units/Nanomolar,1676517,=,1,1,=,,IC50,nM,,54300.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,54.3
,,11009839,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1c[nH]c2ccccc12)C(=O)N[C@@H](Cc1cnc[nH]1)C(=O)NO,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '9.02', 'le': '0.17', 'lle': '3.71', 'sei': '2.38'}",CHEMBL2089167,,CHEMBL2089167,4.23,0,http://www.openphacts.org/units/Nanomolar,1676531,=,1,1,=,,IC50,nM,,58400.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,58.4
,,11009840,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-Gly-Leu-Ala-Nba as substrate incubated for 30 mins prior to substrate addition by fluorescence spectrophotometry,B,,,BAO_0000190,BAO_0000357,single protein format,COc1ccc2c3c([nH]c2c1)C(C)=NCC3.Cl.O,,,CHEMBL2086269,ACS Med Chem Lett,2012,"{'bei': '19.38', 'le': '0.35', 'lle': '1.61', 'sei': '11.11'}",CHEMBL2089157,HARMALINE HYDROCHLORIDE DIHYDRATE,CHEMBL340807,4.15,0,http://www.openphacts.org/units/Nanomolar,1676520,=,1,1,=,,IC50,nM,,70400.0,CHEMBL2079851,Bothrops asper,Snake venom metalloproteinase BaP1,8722,,,IC50,uM,UO_0000065,,70.4

# **Step 3: Bioactivity Data Retrieval (IC50)**
**Retrieve bioactivity data (IC50) for the selected KRAS target.**

**Inspect Missing Values**

In [19]:
df1["standard_type"].isna().sum()

np.int64(0)

**Filter Rows with Valid Bioactivity Values**

In [21]:
df2 = df1[df1["standard_value"].notna()]
df2.head()

,action_type,activity_comment,activity_id,activity_properties,assay_chembl_id,assay_description,assay_type,assay_variant_accession,assay_variant_mutation,bao_endpoint,...,target_organism,target_pref_name,target_tax_id,text_value,toid,type,units,uo_units,upper_value,value
0,None,None,11009832,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,0.5
1,None,None,11009833,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,1.2
2,None,None,11009834,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,4.6
3,None,None,11009835,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,30.9
4,None,None,11009836,[],CHEMBL2091265,Inhibition of snake venom BaP1 using Abz-Ala-G...,B,None,None,BAO_0000190,...,Bothrops asper,Snake venom metalloproteinase BaP1,8722,None,None,IC50,uM,UO_0000065,None,34.2

**Assign Bioactivity Classes**
Define active, intermediate, and inactive classes based on IC50 values.

In [22]:
bioactivity_class = []
for value in df2.standard_value:
    value = float(value)
    if value >= 10000:
        bioactivity_class.append("inactive")
    elif value <= 1000:
        bioactivity_class.append("active")
    else:
        bioactivity_class.append("intermediate")

**Extract Relevant Columns**

In [23]:
molecule_ids = df2.molecule_chembl_id.tolist()
canonical_smiles = df2.canonical_smiles.tolist()
standard_values = df2.standard_value.tolist()

In [24]:
data = list(zip(
    molecule_ids,
    canonical_smiles,
    standard_values,
        bioactivity_class,
))

**Create Preprocessed bioactivity Dataset**

In [25]:

df3 = pd.DataFrame(
    data,
    columns=[
        "molecule_chembl_id",
        "canonical_smiles",
        "standard_value",
        "bioactivity_class",
    ]
)
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL2089170,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@...,500.0,active
1,CHEMBL279786,CNC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](CC(C)C)[C@H...,1200.0,intermediate
2,CHEMBL2089172,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@...,4600.0,intermediate
3,CHEMBL2089171,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@...,30900.0,inactive
4,CHEMBL2089166,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1c[nH]c2ccccc12)C...,34200.0,inactive

**Remove Compounds without Valid SMILES**. Drop rows with **NaN**, **empty** or **None** SMILES values.

In [26]:
df3 = df3.dropna(subset=["canonical_smiles"])
df3 = df3[df3["canonical_smiles"].str.lower() != "none"]
df3 = df3[df3["canonical_smiles"].str.strip() != ""]
df3.head()

,molecule_chembl_id,canonical_smiles,standard_value,bioactivity_class
0,CHEMBL2089170,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@...,500.0,active
1,CHEMBL279786,CNC(=O)[C@H](Cc1ccccc1)NC(=O)[C@H](CC(C)C)[C@H...,1200.0,intermediate
2,CHEMBL2089172,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@...,4600.0,intermediate
3,CHEMBL2089171,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1ccccc1)C(=O)N[C@...,30900.0,inactive
4,CHEMBL2089166,CC(C)C[C@H](NC(=O)[C@@H](N)Cc1c[nH]c2ccccc12)C...,34200.0,inactive

**Save Preprocessed Bioactivity Data.** Save the cleaned dataset to CSV and copy to Google Drive.

In [27]:
df3.to_csv("bioactivity_preprocessed_data.csv", index=False)

!cp bioactivity_preprocessed_data.csv "/content/gdrive/My Drive/Colab Notebooks/data"
!ls "/content/gdrive/My Drive/Colab Notebooks/data"

'/content/gdrive/My Drive/Colab Notebooks/data'

## **End of Part 1: Data Collection and Curation**