## **AI And Biotechnology/Bioinformatics**

## **AI and Drug Discovery Course: QSAR Modeling**
This notebook demonstrates how to collect and preprocess bioactivity data from ChEMBL for QSAR modeling

# **Part 3: Descriptor Calculation**

PaDELPy is a Python wrapper for the PaDEL-Descriptor (molecular descriptor calculation) software.  

It provide the following descriptors/fingerprint:  
* 1444 - 2D Descriptors
* 431 - 3D Descriptors
* 881 bits - PubChem Fingerprints

## **Install PaDELpy**

In [57]:
!pip install padelpy

Requirement already satisfied: padelpy in /usr/local/lib/python3.12/dist-packages (0.1.16)

## **Import libraries**

In [62]:
import pandas as pd
import numpy as np
from google.colab import files
files.upload()
from padelpy import padeldescriptor

Saving df_lipinski.csv to df_lipinski.csv

## **Load dataset**

In [63]:
df = pd.read_csv('df_lipinski.csv')
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL1440883,inactive,4.301030,CC(=O)C1=C(C)NC(SCC(=O)c2ccc(Cl)c(Cl)c2)=C(C#N...,447.343,5.48748,1.0,6.0
1,CHEMBL1471212,inactive,4.434819,CC(=O)N1CCN(c2ccccc2NC(=O)COc2cc(C)ccc2C(C)C)CC1,409.530,3.80442,1.0,4.0
2,CHEMBL1522605,inactive,4.301030,CC1=CC(C)(C)Nc2cc(C)c(C)cc21,201.313,3.91084,1.0,1.0
3,CHEMBL1410132,inactive,4.380628,CC1CCCN(S(=O)(=O)c2ccc(NC(=O)Cn3nnc(-c4ccccc4F...,458.519,2.53850,1.0,6.0
4,CHEMBL1543947,inactive,4.301030,CCCCNC(=O)c1cnc2ccc(S(=O)(=O)Nc3ccc(OCC)cc3)cc...,443.525,3.66980,3.0,6.0

In [64]:
data = df[['canonical_smiles', 'molecule_chembl_id']]
data.head()

                                    canonical_smiles molecule_chembl_id
0  CC(=O)C1=C(C)NC(SCC(=O)c2ccc(Cl)c(Cl)c2)=C(C#N...      CHEMBL1440883
1   CC(=O)N1CCN(c2ccccc2NC(=O)COc2cc(C)ccc2C(C)C)CC1      CHEMBL1471212
2                       CC1=CC(C)(C)Nc2cc(C)c(C)cc21      CHEMBL1522605
3  CC1CCCN(S(=O)(=O)c2ccc(NC(=O)Cn3nnc(-c4ccccc4F...      CHEMBL1410132
4  CCCCNC(=O)c1cnc2ccc(S(=O)(=O)Nc3ccc(OCC)cc3)cc...      CHEMBL1543947

## **Convert to .smi format**

In [65]:
df_smi = data['canonical_smiles'].to_csv('smiles_chembl.smi', index=None, header=None)

In [66]:
! cat smiles_chembl.smi | head

CC(=O)C1=C(C)NC(SCC(=O)c2ccc(Cl)c(Cl)c2)=C(C#N)C1c1ccco1
CC(=O)N1CCN(c2ccccc2NC(=O)COc2cc(C)ccc2C(C)C)CC1
CC1=CC(C)(C)Nc2cc(C)c(C)cc21
CC1CCCN(S(=O)(=O)c2ccc(NC(=O)Cn3nnc(-c4ccccc4F)n3)cc2)C1
CCCCNC(=O)c1cnc2ccc(S(=O)(=O)Nc3ccc(OCC)cc3)cc2c1O
CCCCn1c2c(c3ccccc31)CCc1nonc1-2
CCCO/C(O)=C1\C(C)=NC2=C(C(=O)CCC2)C1c1cccc(OC)c1OC
CCOC(=O)c1c(NC(=O)CSc2nnc(CNc3ccc(F)cc3)o2)sc(C)c1C
CCOC(=O)c1c(NC(=O)Cn2nnc(-c3ccccc3)n2)sc(C(C)=O)c1C
CCOC(=O)c1c(NC(=O)c2cccs2)sc(C)c1CC

## **Calculate molecular Pubchem Fingerprints using "padeldescriptor" function**

In [67]:
padeldescriptor(mol_dir= "smiles_chembl.smi",
                d_file='pubchem_fingerprints.csv',
                fingerprints = True,
                retainorder= True,
                #removesalt = True, standardizetautomers = True, standardizenitro=True
                )

In [68]:
!ls -lh pubchem_fingerprints.csv

-rw-r--r-- 1 root root 85K Feb 22 10:55 pubchem_fingerprints.csv

In [70]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [71]:
df_fingerprint = pd.read_csv("pubchem_fingerprints.csv")
df_fingerprint.head()

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,AUTOGEN_smiles_chembl_1,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,AUTOGEN_smiles_chembl_2,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,AUTOGEN_smiles_chembl_3,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AUTOGEN_smiles_chembl_4,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,AUTOGEN_smiles_chembl_5,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Prepare Dataset for ML**

In [72]:
df.head()

,molecule_chembl_id,bioactivity_class,pIC50,canonical_smiles,MW,LogP,NumHDonors,NumHAcceptors
0,CHEMBL1440883,inactive,4.301030,CC(=O)C1=C(C)NC(SCC(=O)c2ccc(Cl)c(Cl)c2)=C(C#N...,447.343,5.48748,1.0,6.0
1,CHEMBL1471212,inactive,4.434819,CC(=O)N1CCN(c2ccccc2NC(=O)COc2cc(C)ccc2C(C)C)CC1,409.530,3.80442,1.0,4.0
2,CHEMBL1522605,inactive,4.301030,CC1=CC(C)(C)Nc2cc(C)c(C)cc21,201.313,3.91084,1.0,1.0
3,CHEMBL1410132,inactive,4.380628,CC1CCCN(S(=O)(=O)c2ccc(NC(=O)Cn3nnc(-c4ccccc4F...,458.519,2.53850,1.0,6.0
4,CHEMBL1543947,inactive,4.301030,CCCCNC(=O)c1cnc2ccc(S(=O)(=O)Nc3ccc(OCC)cc3)cc...,443.525,3.66980,3.0,6.0

In [73]:
# Select only the columns we need for ML
meta_cols = df[['molecule_chembl_id', 'bioactivity_class', 'pIC50']]

# Reset index to ensure proper alignment
meta_cols = meta_cols.reset_index(drop=True)
df_fingerprint = df_fingerprint.reset_index(drop=True)

# Combine meta data with fingerprints
combined_df = pd.concat([meta_cols, df_fingerprint.drop(df_fingerprint.columns[0], axis=1)], axis=1)

# Inspect the first few rows
combined_df.head()

,molecule_chembl_id,bioactivity_class,pIC50,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,CHEMBL1440883,inactive,4.301030,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,CHEMBL1471212,inactive,4.434819,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,CHEMBL1522605,inactive,4.301030,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,CHEMBL1410132,inactive,4.380628,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,CHEMBL1543947,inactive,4.301030,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## **Save and download the dataset**

In [74]:
# Save as CSV
combined_df.to_csv("QSAR_dataset.csv", index=False)
print("Combined dataset saved as QSAR_dataset.csv")

# Download file in Colab
files.download("QSAR_dataset.csv")

Combined dataset saved as QSAR_dataset.csv

# **Calculate other fingerprints**

## **Download xml Files from Github**

In [75]:
!wget https://github.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/raw/main/padel_descriptors_xml.zip

--2026-02-22 11:02:39--  https://github.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/raw/main/padel_descriptors_xml.zip
Resolving github.com (github.com)... 20.205.243.166
Connecting to github.com (github.com)|20.205.243.166|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/main/padel_descriptors_xml.zip [following]
--2026-02-22 11:02:40--  https://raw.githubusercontent.com/AI-Biotechnology-Bioinformatics/Drug_Discovery_AI_Course_2026/main/padel_descriptors_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: ‘padel_descriptors_xml.zip’

padel_descriptors_x 100%[===================>]  10.62K  --.-KB/s    in 0s

2026-02-22 11:02:40 (79.0 MB/s) - ‘padel_descriptors_xml.zip’ saved [10871/10871]

## **Unzip all files**

In [76]:
!unzip padel_descriptors_xml.zip

Archive:  padel_descriptors_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

## **Calculate Fingerprints**

In [77]:
# Specify the XML file for SubstructureFingerprinter directly
Substruc_fp = "SubstructureFingerprinter.xml"

# Calculate Substructure fingerprints
padeldescriptor(
    mol_dir='smiles_chembl.smi',
    d_file='Substructure_fingerprints.csv',
    fingerprints=True,
    descriptortypes= Substruc_fp,
    retainorder=True
    # removesalt=True, standardizetautomers=True
)